#!/bin/bash
# stop <option> [pid]
# options:
#  -a : stop all
#  -p : pid, -p <pid>
# use show to get the pid

if [[ $# -lt 1 ]]
then
  echo "usage:"
  exit
fi

if ! [[ -f "$2" ]]; then
  echo "$2 does not exist"
  exit
fi

RECORD=pid
if ! [[ -d "$RECORD" ]]; then
  mkdir $RECORD
fi

case "$1" in
-a) echo "stop all"
    RECORD_LEN=$(ls -l ${RECORD} | grep ${EXECUTABLE}-process | wc -l)
    if [[ $RECORD_LEN -gt 0 ]]; then
      RUNNING_LIST=$(ls -l ${RECORD} | grep ${EXECUTABLE}-process | rev | cut -d' ' -f1 | rev)
      for RUNNING_PROCESS in $RUNNING_LIST; do
        PID=$(echo ${RUNNING_PROCESS} | cut -d'.' -f2)
        kill -9 $PID
      done
    fi
    ;;
-p) echo "stopping $2"
    kill -9 $2
    ;;
*) echo "Invalid option"
   ;;
esac
